#!/usr/bin/env bash
# =============================================================================
# optimize-pocketbeagle-boot.sh — PocketBeagle Debian Boot Optimizer
# Version: 1.0.0
#
# GOAL: Aggressively strip a PocketBeagle image to a dotnet-appliance baseline.
#       dotnet is the only first-class user service. Everything else is removed
#       from the critical boot path.
#
# USAGE:
#   sudo ./optimize-pocketbeagle-boot.sh --dry-run    # Preview actions
#   sudo ./optimize-pocketbeagle-boot.sh --apply      # Apply all changes
#   sudo ./optimize-pocketbeagle-boot.sh --restore    # Delegate to restore script
#
# SAFETY:
#   - Idempotent: safe to run multiple times
#   - Never blindly deletes files (checks state first)
#   - All changes logged to /root/boot-diagnostics/
#   - Full restore via restore-pocketbeagle-boot.sh (generated by --apply)
#   - ARM-only guard prevents accidental execution on host machine
#
# See: docs/superpowers/specs/2026-04-25-pocketbeagle-boot-design.md
# =============================================================================

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
readonly SCRIPT_VERSION="1.0.0"
readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Diagnostic output directories (primary preferred, fallback if not present)
readonly DIAG_DIR_PRIMARY="/boot/firmware/boot-diagnostics"
readonly DIAG_DIR_FALLBACK="/root/boot-diagnostics"

# All logs and manifest go here (root home — always writable)
readonly LOG_DIR="/root/boot-diagnostics"

# Manifest tracks exactly what this script changed (used by restore)
readonly MANIFEST_FILE="${LOG_DIR}/.applied-manifest"

# Files this script may create on the device
readonly NM_CONF="/etc/NetworkManager/conf.d/99-no-auto.conf"
readonly BLACKLIST_CONF="/etc/modprobe.d/rapidbeagle-blacklist.conf"
readonly USB0_STATIC="/etc/network/interfaces.d/usb0-static"
readonly HEARTBEAT_SERVICE="/etc/systemd/system/pb-heartbeat.service"
readonly HEARTBEAT_SCRIPT="/usr/local/sbin/pb-heartbeat"
readonly MARKER_SERVICE="/etc/systemd/system/pb-boot-marker.service"
readonly DOTNET_SERVICE="/etc/systemd/system/dotnet-app.service"
readonly RESTORE_SCRIPT="${SCRIPT_DIR}/restore-pocketbeagle-boot.sh"

# USR0 LED sysfs path (beaglebone:green:usr0 — reclaimed from kernel heartbeat)
readonly LED_PATH="/sys/class/leds/beaglebone:green:usr0"

# ── Kill list — disabled only if present AND currently enabled ─────────────────
# Protected services (ssh, networking, getty, usb-gadget) are NOT in this list.
KILL_LIST=(
    # BeagleBoard IDE and demo services — large node.js stacks, not needed
    cloud9 bonescript bonescript-autorun gateone node-red code-server
    # Web servers — no web UI needed on a dotnet appliance
    apache2 nginx cockpit lighttpd
    # mDNS/discovery — avahi broadcasts presence; wastes boot time, not needed
    avahi-daemon avahi-dnsconfd
    # Network-wait blockers — these stall multi-user.target waiting for DHCP
    # dotnet manages network; we don't need boot to block on DHCP lease
    connman-wait-online NetworkManager-wait-online systemd-networkd-wait-online
    # Bluetooth stack — no BT needed; USB MIDI uses USB host port directly
    bluetooth bluealsa btattach hciuart
    # Printing — not applicable on embedded appliance
    cups cups-browsed
    # Other non-essential system services
    ModemManager   # modem/cellular — not used
    packagekit     # package manager D-Bus daemon — not needed at runtime
    snapd          # snap package daemon — heavy, not needed
    apt-daily      # background apt updates — breaks predictability on appliance
    apt-daily-upgrade  # same
)

# ── Mode state ────────────────────────────────────────────────────────────────
DRY_RUN=0    # 1 = preview only, 0 = apply changes
MODE=""      # --dry-run | --apply | --restore
LOG_FILE=""  # set by setup_logging()
DIAG_DIR=""  # set by run_diagnostics()

# ── Logging helpers ───────────────────────────────────────────────────────────

log() {
    # Log to stdout and to log file (once log file is set up)
    local msg
    msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
    echo "$msg"
    [[ -n "${LOG_FILE:-}" ]] && echo "$msg" >> "$LOG_FILE"
}

log_action() {
    # Use for every change this script would make — respects DRY_RUN
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "[DRY-RUN] Would: $*"
    else
        log "[ACTION]  $*"
    fi
}

log_skip() { log "[SKIP]    $*"; }
log_ok()   { log "[OK]      $*"; }
log_warn() { log "[WARN]    $*"; }
log_err()  { log "[ERROR]   $*" >&2; }

# ── Arg parsing ───────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: sudo $SCRIPT_NAME [--dry-run | --apply | --restore]

  --dry-run   Preview all actions. Diagnostic files ARE written (read-only
              observations). No configuration changes are made.

  --apply     Apply all boot optimizations. Generates restore script.

  --restore   Delegate to restore-pocketbeagle-boot.sh (must exist from a
              prior --apply run).

  --help      Show this message.

See docs/superpowers/specs/2026-04-25-pocketbeagle-boot-design.md for details.
EOF
}

parse_args() {
    if [[ $# -ne 1 ]]; then
        usage
        exit 1
    fi

    case "$1" in
        --dry-run) MODE="--dry-run"; DRY_RUN=1 ;;
        --apply)   MODE="--apply";   DRY_RUN=0 ;;
        --restore) MODE="--restore"; DRY_RUN=0 ;;
        --help|-h) usage; exit 0 ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            usage
            exit 1
            ;;
    esac
}

# ── Guard rails ───────────────────────────────────────────────────────────────

check_guards() {
    # Guard 1: Must run as root (systemctl disable requires it)
    if [[ "$EUID" -ne 0 ]]; then
        echo "ERROR: Must be run as root." >&2
        echo "       Run: sudo $SCRIPT_NAME $MODE" >&2
        exit 1
    fi

    # Guard 2: ARM-only — prevents accidental execution on Windows/WSL host.
    # The kill list would disable services on your development machine.
    local arch
    arch="$(uname -m)"
    if [[ "$arch" != arm* && "$arch" != aarch64* ]]; then
        echo "ERROR: ARM architecture required (detected: $arch)." >&2
        echo "       This script must run ON the PocketBeagle, not on your host." >&2
        exit 1
    fi

    log_ok "Guard checks passed (root=yes, arch=$arch)"
}

# ── Logging setup ─────────────────────────────────────────────────────────────

setup_logging() {
    mkdir -p "$LOG_DIR"
    LOG_FILE="${LOG_DIR}/optimize-$(date +%Y-%m-%d).log"
    log "============================================================"
    log "PocketBeagle Boot Optimizer v${SCRIPT_VERSION}"
    log "Mode:     ${MODE}"
    log "Dry run:  ${DRY_RUN}"
    log "Host:     $(uname -n)"
    log "Arch:     $(uname -m)"
    log "Kernel:   $(uname -r)"
    log "Date:     $(date)"
    log "Log file: ${LOG_FILE}"
    log "============================================================"
}

# ── Phase 1: Diagnostic Snapshot ─────────────────────────────────────────────
# Runs in ALL modes (dry-run and apply). Writes read-only system observations.
# Saved to /boot/firmware/boot-diagnostics/ if available, else /root/boot-diagnostics/

run_diagnostics() {
    log "--- Phase 1: Diagnostic Snapshot ---"

    # Choose diagnostic output directory
    if [[ -d "/boot/firmware" ]]; then
        DIAG_DIR="$DIAG_DIR_PRIMARY"
    else
        DIAG_DIR="$DIAG_DIR_FALLBACK"
    fi
    mkdir -p "$DIAG_DIR"
    log_ok "Diagnostic output: $DIAG_DIR"

    # Helper: run a command, save output, log result
    diag_run() {
        local label="$1"
        local outfile="${DIAG_DIR}/${label}"
        shift
        log "  Capturing: $label"
        if "$@" > "$outfile" 2>&1; then
            log_ok "  Saved: $outfile"
        else
            log_warn "  Command returned non-zero for $label (output still saved)"
        fi
    }

    # Boot timing
    diag_run "systemd-analyze.txt"           systemd-analyze
    diag_run "systemd-blame.txt"             systemd-analyze blame
    diag_run "systemd-critical-chain.txt"    systemd-analyze critical-chain

    # Journal warnings from this boot
    diag_run "journal-warnings.txt"          journalctl -b -p warning --no-pager

    # Service state
    diag_run "services-enabled.txt"          systemctl list-unit-files --state=enabled --no-pager
    diag_run "services-failed.txt"           systemctl --failed --no-pager

    # Network-wait units specifically (common boot bottleneck)
    {
        for svc in connman-wait-online NetworkManager-wait-online systemd-networkd-wait-online; do
            echo "=== $svc ==="
            systemctl status "$svc" --no-pager 2>&1 || true
            echo ""
        done
    } > "${DIAG_DIR}/network-wait-status.txt"
    log_ok "  Saved: network-wait-status.txt"

    # USB gadget status (must survive optimizations)
    {
        for svc in bb-usb-gadgets usb-gadget; do
            echo "=== $svc ==="
            systemctl status "$svc" --no-pager 2>&1 || true
            echo ""
        done
    } > "${DIAG_DIR}/usb-gadget-status.txt"
    log_ok "  Saved: usb-gadget-status.txt"

    # Full loaded module list (used to identify 3rd party driver candidates)
    diag_run "lsmod.txt"                     lsmod

    log_ok "Phase 1 complete. Diagnostics in: $DIAG_DIR"
}

# ── Phase 2: Service Disabling ────────────────────────────────────────────────
# Disables services from KILL_LIST that both exist AND are currently enabled.
# Records each disabled service in MANIFEST_FILE for restore.
# Protected services (ssh, networking, getty, usb-gadget) are not in KILL_LIST.

disable_services() {
    log "--- Phase 2: Service Disabling ---"

    # Ensure manifest directory exists
    mkdir -p "$LOG_DIR"

    # Initialise manifest section (idempotent: append only new entries)
    if [[ ! -f "$MANIFEST_FILE" ]]; then
        cat > "$MANIFEST_FILE" <<'MANIFEST'
# RapidBeagle applied-manifest
# Format: TYPE|VALUE
# This file is read by restore-pocketbeagle-boot.sh
MANIFEST
    fi

    local disabled_count=0

    for svc in "${KILL_LIST[@]}"; do
        # Check the .service unit exists on this image
        if ! systemctl list-unit-files "${svc}.service" 2>/dev/null | grep -q "${svc}.service"; then
            log_skip "Service not present: ${svc}.service"
            continue
        fi

        # Check it is currently enabled (don't record already-disabled services)
        local state
        state="$(systemctl is-enabled "${svc}.service" 2>/dev/null || echo "not-found")"
        if [[ "$state" != "enabled" && "$state" != "static" ]]; then
            log_skip "Already not enabled (${state}): ${svc}.service"
            continue
        fi

        log_action "Disable and stop: ${svc}.service (was: ${state})"

        if [[ "$DRY_RUN" -eq 0 ]]; then
            systemctl disable --now "${svc}.service" 2>&1 | while IFS= read -r line; do
                log "    systemctl: $line"
            done || log_warn "  disable returned non-zero for ${svc} (may already be stopped)"

            # Record in manifest so restore knows exactly what to re-enable
            if ! grep -qF "SERVICE|${svc}" "$MANIFEST_FILE" 2>/dev/null; then
                echo "SERVICE|${svc}" >> "$MANIFEST_FILE"
            fi
        fi

        (( disabled_count++ )) || true
    done

    log_ok "Phase 2 complete. Services acted on: ${disabled_count}"
}

# ── Phase 3: Kernel Module Blacklist ─────────────────────────────────────────
# Writes /etc/modprobe.d/rapidbeagle-blacklist.conf to prevent unnecessary
# kernel modules from loading at boot.
#
# SPEC CORRECTION: snd_pcm is NOT blacklisted. snd_usb_audio (USB MIDI class
# driver) depends on snd_pcm. Blacklisting it would silently break the USB
# MIDI controller plugged into the host port.
#
# Protected MIDI modules (never blacklisted):
#   snd_rawmidi, snd_usbmidi_lib, snd_usb_audio, snd_seq, snd_seq_midi,
#   snd_seq_midi_event, snd_pcm
#
# Protected network/bridge modules (never blacklisted):
#   cfg80211, mac80211, brcmfmac, rtl8*, ath*, iwlwifi,
#   bridge, br_netfilter, 8021q, xhci_hcd, ehci_hcd

write_module_blacklist() {
    log "--- Phase 3: Kernel Module Blacklist ---"

    # Generate the desired blacklist content
    local new_content
    new_content="$(cat <<'BLACKLIST'
# /etc/modprobe.d/rapidbeagle-blacklist.conf
# Generated by optimize-pocketbeagle-boot.sh
# Remove this file with: restore-pocketbeagle-boot.sh
# Or manually: rm /etc/modprobe.d/rapidbeagle-blacklist.conf && update-initramfs -u

# ── Bluetooth ────────────────────────────────────────────────────────────────
# No Bluetooth needed. USB MIDI uses USB host port via snd_usb_audio, not BT.
blacklist btusb
blacklist bluetooth
blacklist hci_uart
blacklist btbcm
blacklist btintel
blacklist bnep
blacklist rfcomm

# ── Intel HDA Audio ──────────────────────────────────────────────────────────
# Intel HDA is x86 hardware — not present on PocketBeagle (TI AM335x).
# Safe to blacklist; prevents any future accidental load.
blacklist snd_hda_intel
blacklist snd_hda_codec_generic
blacklist snd_hda_codec_hdmi

# ── AM335x SoC Audio Codecs (McASP / I2S) ───────────────────────────────────
# PocketBeagle has AM335x McASP I2S audio hardware, but we only use USB MIDI.
# Blacklist the I2S/codec drivers to avoid loading them at boot.
# NOTE: snd_pcm is intentionally NOT blacklisted — snd_usb_audio depends on it.
blacklist snd_soc_davinci_mcasp
blacklist snd_soc_am33xx
blacklist snd_soc_tlv320aic3x
blacklist snd_soc_simple_card
BLACKLIST
)"

    # Idempotency: skip if file already contains identical content
    if [[ -f "$BLACKLIST_CONF" ]]; then
        local existing_content
        existing_content="$(cat "$BLACKLIST_CONF")"
        if [[ "$existing_content" == "$new_content" ]]; then
            log_skip "Blacklist file already up to date: $BLACKLIST_CONF"
            return
        fi
        log_action "Update existing blacklist file: $BLACKLIST_CONF"
    else
        log_action "Create blacklist file: $BLACKLIST_CONF"
    fi

    if [[ "$DRY_RUN" -eq 0 ]]; then
        echo "$new_content" > "$BLACKLIST_CONF"

        # Record in manifest for restore
        if ! grep -qF "BLACKLIST|${BLACKLIST_CONF}" "$MANIFEST_FILE" 2>/dev/null; then
            echo "BLACKLIST|${BLACKLIST_CONF}" >> "$MANIFEST_FILE"
        fi

        # Rebuild initramfs so blacklist takes effect on next boot
        log_action "Rebuilding initramfs (update-initramfs -u) — this may take 30-60 seconds"
        if command -v update-initramfs &>/dev/null; then
            update-initramfs -u 2>&1 | while IFS= read -r line; do log "    initramfs: $line"; done
            log_ok "initramfs rebuilt"
        else
            log_warn "update-initramfs not found — blacklist will take effect on next cold boot"
        fi
    fi

    log_ok "Phase 3 complete."
}

# ── Phase 4: Kernel Cmdline Optimization ─────────────────────────────────────
# Appends "quiet loglevel=3" to the kernel boot arguments.
# This suppresses printk console output, reducing serial I/O overhead during boot.
#
# Detects cmdline file automatically:
#   1. /boot/firmware/extlinux/extlinux.conf  (BeagleBone Debian >= Buster)
#   2. /boot/cmdline.txt                      (older images / Raspberry Pi style)
#
# Backs up original file as .bak before patching.
# Idempotent: skips if "quiet" is already present in the cmdline.

patch_kernel_cmdline() {
    log "--- Phase 4: Kernel Cmdline Optimization ---"

    # Detect which cmdline file is present
    local cmdline_file=""
    if [[ -f "/boot/firmware/extlinux/extlinux.conf" ]]; then
        cmdline_file="/boot/firmware/extlinux/extlinux.conf"
        log_ok "Detected extlinux config: $cmdline_file"
    elif [[ -f "/boot/cmdline.txt" ]]; then
        cmdline_file="/boot/cmdline.txt"
        log_ok "Detected cmdline.txt: $cmdline_file"
    else
        log_warn "No kernel cmdline file found at known paths — skipping Phase 4"
        log_warn "Checked: /boot/firmware/extlinux/extlinux.conf, /boot/cmdline.txt"
        return
    fi

    # Idempotency: skip if "quiet" is already present
    if grep -q "quiet" "$cmdline_file"; then
        log_skip "'quiet' already present in $cmdline_file — skipping"
        return
    fi

    log_action "Patch $cmdline_file — append 'quiet loglevel=3' to kernel args"

    if [[ "$DRY_RUN" -eq 0 ]]; then
        # Backup original before any modifications
        local bak_file="${cmdline_file}.bak"
        if [[ ! -f "$bak_file" ]]; then
            cp "$cmdline_file" "$bak_file"
            log_ok "Backup created: $bak_file"
        else
            log_skip "Backup already exists: $bak_file"
        fi

        # Patch: For extlinux.conf, the kernel args are on the "append" line.
        # For cmdline.txt, the entire file is one line of kernel args.
        if [[ "$cmdline_file" == *"extlinux.conf" ]]; then
            # Append to the "append" directive line (the kernel arguments line)
            sed -i '/^\s*append\s/s/$/ quiet loglevel=3/' "$cmdline_file"
            log_ok "Patched extlinux append line"
        else
            # cmdline.txt: single line, append args to end
            sed -i 's/$/ quiet loglevel=3/' "$cmdline_file"
            log_ok "Patched cmdline.txt"
        fi

        # Record in manifest for restore
        if ! grep -qF "CMDLINE|${cmdline_file}" "$MANIFEST_FILE" 2>/dev/null; then
            echo "CMDLINE|${cmdline_file}" >> "$MANIFEST_FILE"
        fi

        # Verify patch
        if grep -q "quiet" "$cmdline_file"; then
            log_ok "Verified: 'quiet' present in $cmdline_file"
        else
            log_err "Patch verification failed — 'quiet' not found after edit"
            exit 1
        fi
    fi

    log_ok "Phase 4 complete."
}

# ── Main (stub — filled in Task 12) ──────────────────────────────────────────

main() {
    parse_args "$@"
    check_guards
    setup_logging

    # Handle --restore mode immediately — delegate to restore script
    if [[ "$MODE" == "--restore" ]]; then
        if [[ ! -f "$RESTORE_SCRIPT" ]]; then
            log_err "Restore script not found: $RESTORE_SCRIPT"
            log_err "Run --apply first to generate it."
            exit 1
        fi
        log "Delegating to restore script: $RESTORE_SCRIPT"
        exec bash "$RESTORE_SCRIPT"
    fi

    run_diagnostics

    if [[ "$DRY_RUN" -eq 0 ]]; then
        log "Proceeding with --apply phases..."
    else
        # In dry-run, still walk through all phases for preview output
        DRY_RUN=1
    fi

    disable_services
    write_module_blacklist
    patch_kernel_cmdline

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "DRY-RUN complete. No configuration changes were made."
        log "Diagnostic files written to: ${DIAG_DIR:-$DIAG_DIR_FALLBACK}"
        exit 0
    fi
}

main "$@"
