#!/usr/bin/env bash
# =============================================================================
# optimize-pocketbeagle-boot.sh — PocketBeagle Debian Boot Optimizer
# Version: 1.0.0
#
# GOAL: Aggressively strip a PocketBeagle image to a dotnet-appliance baseline.
#       dotnet is the only first-class user service. Everything else is removed
#       from the critical boot path.
#
# USAGE:
#   sudo ./optimize-pocketbeagle-boot.sh --dry-run    # Preview actions
#   sudo ./optimize-pocketbeagle-boot.sh --apply      # Apply all changes
#   sudo ./optimize-pocketbeagle-boot.sh --restore    # Delegate to restore script
#
# SAFETY:
#   - Idempotent: safe to run multiple times
#   - Never blindly deletes files (checks state first)
#   - All changes logged to /root/boot-diagnostics/
#   - Full restore via restore-pocketbeagle-boot.sh (generated by --apply)
#   - ARM-only guard prevents accidental execution on host machine
#
# See: docs/superpowers/specs/2026-04-25-pocketbeagle-boot-design.md
# =============================================================================

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
readonly SCRIPT_VERSION="1.0.0"
readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Diagnostic output directories (primary preferred, fallback if not present)
readonly DIAG_DIR_PRIMARY="/boot/firmware/boot-diagnostics"
readonly DIAG_DIR_FALLBACK="/root/boot-diagnostics"

# All logs and manifest go here (root home — always writable)
readonly LOG_DIR="/root/boot-diagnostics"

# Manifest tracks exactly what this script changed (used by restore)
readonly MANIFEST_FILE="${LOG_DIR}/.applied-manifest"

# Files this script may create on the device
readonly NM_CONF="/etc/NetworkManager/conf.d/99-no-auto.conf"
readonly BLACKLIST_CONF="/etc/modprobe.d/rapidbeagle-blacklist.conf"
readonly USB0_STATIC="/etc/network/interfaces.d/usb0-static"
readonly HEARTBEAT_SERVICE="/etc/systemd/system/pb-heartbeat.service"
readonly HEARTBEAT_SCRIPT="/usr/local/sbin/pb-heartbeat"
readonly MARKER_SERVICE="/etc/systemd/system/pb-boot-marker.service"
readonly DOTNET_SERVICE="/etc/systemd/system/dotnet-app.service"
readonly RESTORE_SCRIPT="${SCRIPT_DIR}/restore-pocketbeagle-boot.sh"

# USR0 LED sysfs path (beaglebone:green:usr0 — reclaimed from kernel heartbeat)
readonly LED_PATH="/sys/class/leds/beaglebone:green:usr0"

# ── Kill list — disabled only if present AND currently enabled ─────────────────
# Protected services (ssh, networking, getty, usb-gadget) are NOT in this list.
KILL_LIST=(
    # BeagleBoard IDE and demo services — large node.js stacks, not needed
    cloud9 bonescript bonescript-autorun gateone node-red code-server
    # Web servers — no web UI needed on a dotnet appliance
    apache2 nginx cockpit lighttpd
    # mDNS/discovery — avahi broadcasts presence; wastes boot time, not needed
    avahi-daemon avahi-dnsconfd
    # Network-wait blockers — these stall multi-user.target waiting for DHCP
    # dotnet manages network; we don't need boot to block on DHCP lease
    connman-wait-online NetworkManager-wait-online systemd-networkd-wait-online
    # Bluetooth stack — no BT needed; USB MIDI uses USB host port directly
    bluetooth bluealsa btattach hciuart
    # Printing — not applicable on embedded appliance
    cups cups-browsed
    # Other non-essential system services
    ModemManager   # modem/cellular — not used
    packagekit     # package manager D-Bus daemon — not needed at runtime
    snapd          # snap package daemon — heavy, not needed
    apt-daily      # background apt updates — breaks predictability on appliance
    apt-daily-upgrade  # same
)

# ── Mode state ────────────────────────────────────────────────────────────────
DRY_RUN=0    # 1 = preview only, 0 = apply changes
MODE=""      # --dry-run | --apply | --restore
LOG_FILE=""  # set by setup_logging()
DIAG_DIR=""  # set by run_diagnostics()

# ── Logging helpers ───────────────────────────────────────────────────────────

log() {
    # Log to stdout and to log file (once log file is set up)
    local msg
    msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
    echo "$msg"
    [[ -n "${LOG_FILE:-}" ]] && echo "$msg" >> "$LOG_FILE"
}

log_action() {
    # Use for every change this script would make — respects DRY_RUN
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "[DRY-RUN] Would: $*"
    else
        log "[ACTION]  $*"
    fi
}

log_skip() { log "[SKIP]    $*"; }
log_ok()   { log "[OK]      $*"; }
log_warn() { log "[WARN]    $*"; }
log_err()  { log "[ERROR]   $*" >&2; }

# ── Arg parsing ───────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: sudo $SCRIPT_NAME [--dry-run | --apply | --restore]

  --dry-run   Preview all actions. Diagnostic files ARE written (read-only
              observations). No configuration changes are made.

  --apply     Apply all boot optimizations. Generates restore script.

  --restore   Delegate to restore-pocketbeagle-boot.sh (must exist from a
              prior --apply run).

  --help      Show this message.

See docs/superpowers/specs/2026-04-25-pocketbeagle-boot-design.md for details.
EOF
}

parse_args() {
    if [[ $# -ne 1 ]]; then
        usage
        exit 1
    fi

    case "$1" in
        --dry-run) MODE="--dry-run"; DRY_RUN=1 ;;
        --apply)   MODE="--apply";   DRY_RUN=0 ;;
        --restore) MODE="--restore"; DRY_RUN=0 ;;
        --help|-h) usage; exit 0 ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            usage
            exit 1
            ;;
    esac
}

# ── Guard rails ───────────────────────────────────────────────────────────────

check_guards() {
    # Guard 1: Must run as root (systemctl disable requires it)
    if [[ "$EUID" -ne 0 ]]; then
        echo "ERROR: Must be run as root." >&2
        echo "       Run: sudo $SCRIPT_NAME $MODE" >&2
        exit 1
    fi

    # Guard 2: ARM-only — prevents accidental execution on Windows/WSL host.
    # The kill list would disable services on your development machine.
    local arch
    arch="$(uname -m)"
    if [[ "$arch" != arm* && "$arch" != aarch64* ]]; then
        echo "ERROR: ARM architecture required (detected: $arch)." >&2
        echo "       This script must run ON the PocketBeagle, not on your host." >&2
        exit 1
    fi

    log_ok "Guard checks passed (root=yes, arch=$arch)"
}

# ── Logging setup ─────────────────────────────────────────────────────────────

setup_logging() {
    mkdir -p "$LOG_DIR"
    LOG_FILE="${LOG_DIR}/optimize-$(date +%Y-%m-%d).log"
    log "============================================================"
    log "PocketBeagle Boot Optimizer v${SCRIPT_VERSION}"
    log "Mode:     ${MODE}"
    log "Dry run:  ${DRY_RUN}"
    log "Host:     $(uname -n)"
    log "Arch:     $(uname -m)"
    log "Kernel:   $(uname -r)"
    log "Date:     $(date)"
    log "Log file: ${LOG_FILE}"
    log "============================================================"
}

# ── Main (stub — filled in Task 12) ──────────────────────────────────────────

main() {
    parse_args "$@"
    check_guards
    setup_logging

    # Handle --restore mode immediately — delegate to restore script
    if [[ "$MODE" == "--restore" ]]; then
        if [[ ! -f "$RESTORE_SCRIPT" ]]; then
            log_err "Restore script not found: $RESTORE_SCRIPT"
            log_err "Run --apply first to generate it."
            exit 1
        fi
        log "Delegating to restore script: $RESTORE_SCRIPT"
        exec bash "$RESTORE_SCRIPT"
    fi

    log "Phases will be added in subsequent tasks."
}

main "$@"
