#!/usr/bin/env bash
# restore-pocketbeagle-boot.sh — TEMPLATE
#
# This file is a placeholder committed to the repo.
# The LIVE version is generated by:
#   sudo ./optimize-pocketbeagle-boot.sh --apply
#
# The generated version contains the exact list of services disabled and
# files created on YOUR device, read from /root/boot-diagnostics/.applied-manifest
#
# Usage: sudo ./restore-pocketbeagle-boot.sh
#    or: sudo ./optimize-pocketbeagle-boot.sh --restore

echo "This is the template restore script from the repo."
echo "The live version is generated by: sudo ./optimize-pocketbeagle-boot.sh --apply"
echo "If you have already run --apply, the live version should be in this directory."
exit 1
